package bibliotecagrafos.visao;

import bibliotecagrafos.Aresta;
import bibliotecagrafos.Grafo;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.AWTError;
import java.io.File;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextPane;

/**
 *
 * @author  Daniel Freitas Martins - 2304
 *          Naiara Cristiane dos Reis Diniz - 3005
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    Grafo grafo;
    private String nome_arquivo_lido;
    public static final String FILE_SEPARATOR = System.getProperty("file.separator");
    public static final File FILE_USER_DIR = new File(System.getProperty("user.dir"));
    public static final String OUTPUT_PATH = FILE_USER_DIR.getAbsolutePath() + FILE_SEPARATOR + "output";
    private static final String CAMINHO_ICONE = "/misc/logo.png";
    
    private void mudaIcone() {
        try{
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(CAMINHO_ICONE)));
        } catch(AWTError | NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Não foi possível carregar o ícone...");
        }
    }

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {        
        initComponents();
        mudaIcone();
        jFileChooser1.setCurrentDirectory(FILE_USER_DIR);
        jFileChooser2.setCurrentDirectory(FILE_USER_DIR);
        
        
        grafo = new Grafo();
        nome_arquivo_lido = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSaida = new javax.swing.JTextArea();
        btnLimparTextoSaida = new javax.swing.JButton();
        btnEscreverEmArquivo = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtOrdemGrafo = new javax.swing.JTextField();
        btnGetOrdemGrafo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTamanhoGrafo = new javax.swing.JTextField();
        btnGetTamanhoGrafo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnGetGrauVerticeEVizinhos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGrauVerticeEVizinhos = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnIsBipartido = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnIsArticulacao = new javax.swing.JButton();
        txtIsArticulacao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnIsPonte = new javax.swing.JButton();
        txtIsPonte = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtIsBipartido = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnBuscaProfundidade = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBuscaProfundidade = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        btnComponentesConexas = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtComponentesConexas = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        btnBuscaLargura = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtBuscaLargura = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnDistanciaECaminhoMinimo = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtDistanciaECaminhoMinimo = new javax.swing.JTextArea();
        cbCalcularFloydCompleto = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnArvoreGeradoraMinima = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtArvoreGeradoraMinima = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        btnCadeiaEuleriana = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtCadeiaEuleriana = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        btnConjuntoIndependente = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtConjuntoIndependente = new javax.swing.JTextArea();
        cbConjuntoIndependenteOrdenacaoAleatoria = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtVerticeOrigemAresta = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        txtVerticeDestinoAresta = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        txtVerticeUnitario = new javax.swing.JSpinner();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtArquivoEntrada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSelecionarArquivoSaida = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtArquivoSaida = new javax.swing.JTextField();
        btnSelecionarArquivoEntrada = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca - Grafos");
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saída", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        txtSaida.setColumns(20);
        txtSaida.setRows(5);
        jScrollPane1.setViewportView(txtSaida);

        btnLimparTextoSaida.setText("Limpar texto de saída");
        btnLimparTextoSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTextoSaidaActionPerformed(evt);
            }
        });

        btnEscreverEmArquivo.setText("Escrever em arquivo");
        btnEscreverEmArquivo.setEnabled(false);
        btnEscreverEmArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscreverEmArquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnLimparTextoSaida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEscreverEmArquivo)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparTextoSaida)
                    .addComponent(btnEscreverEmArquivo))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operações", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Ordem:");

        txtOrdemGrafo.setEditable(false);
        txtOrdemGrafo.setBackground(new java.awt.Color(255, 255, 255));

        btnGetOrdemGrafo.setText("Obter");
        btnGetOrdemGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetOrdemGrafoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Tamanho:");

        txtTamanhoGrafo.setEditable(false);
        txtTamanhoGrafo.setBackground(new java.awt.Color(255, 255, 255));

        btnGetTamanhoGrafo.setText("Obter");
        btnGetTamanhoGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTamanhoGrafoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Grau do vértice e Vizinhos:");

        btnGetGrauVerticeEVizinhos.setText("Obter");
        btnGetGrauVerticeEVizinhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetGrauVerticeEVizinhosActionPerformed(evt);
            }
        });

        txtGrauVerticeEVizinhos.setEditable(false);
        txtGrauVerticeEVizinhos.setColumns(20);
        txtGrauVerticeEVizinhos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtGrauVerticeEVizinhos.setRows(5);
        jScrollPane2.setViewportView(txtGrauVerticeEVizinhos);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("É bipartido?");

        btnIsBipartido.setText("Obter");
        btnIsBipartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsBipartidoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("É articulação?");

        btnIsArticulacao.setText("Obter");
        btnIsArticulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsArticulacaoActionPerformed(evt);
            }
        });

        txtIsArticulacao.setEditable(false);
        txtIsArticulacao.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("É ponte?");

        btnIsPonte.setText("Obter");
        btnIsPonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsPonteActionPerformed(evt);
            }
        });

        txtIsPonte.setEditable(false);
        txtIsPonte.setBackground(new java.awt.Color(255, 255, 255));

        txtIsBipartido.setEditable(false);
        txtIsBipartido.setColumns(20);
        txtIsBipartido.setRows(5);
        jScrollPane6.setViewportView(txtIsBipartido);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGetOrdemGrafo)
                        .addGap(13, 13, 13)
                        .addComponent(txtOrdemGrafo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGetTamanhoGrafo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTamanhoGrafo))
                    .addComponent(jScrollPane2)
                    .addComponent(txtIsArticulacao)
                    .addComponent(txtIsPonte)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGetGrauVerticeEVizinhos))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIsPonte))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIsArticulacao)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIsBipartido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOrdemGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetOrdemGrafo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTamanhoGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetTamanhoGrafo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnGetGrauVerticeEVizinhos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btnIsBipartido))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnIsArticulacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIsArticulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnIsPonte))
                .addGap(4, 4, 4)
                .addComponent(txtIsPonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Página 1", jPanel2);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Busca em profundidade:");

        btnBuscaProfundidade.setText("Executar");
        btnBuscaProfundidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaProfundidadeActionPerformed(evt);
            }
        });

        txtBuscaProfundidade.setEditable(false);
        txtBuscaProfundidade.setColumns(20);
        txtBuscaProfundidade.setRows(5);
        jScrollPane3.setViewportView(txtBuscaProfundidade);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Componentes conexas:");

        btnComponentesConexas.setText("Executar");
        btnComponentesConexas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComponentesConexasActionPerformed(evt);
            }
        });

        txtComponentesConexas.setEditable(false);
        txtComponentesConexas.setColumns(20);
        txtComponentesConexas.setRows(5);
        jScrollPane4.setViewportView(txtComponentesConexas);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Busca em largura:");

        btnBuscaLargura.setText("Executar");
        btnBuscaLargura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaLarguraActionPerformed(evt);
            }
        });

        txtBuscaLargura.setEditable(false);
        txtBuscaLargura.setColumns(20);
        txtBuscaLargura.setRows(5);
        jScrollPane5.setViewportView(txtBuscaLargura);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaProfundidade))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaLargura))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnComponentesConexas)))
                        .addGap(0, 111, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnBuscaProfundidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(btnBuscaLargura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnComponentesConexas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Página 2", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Distância, caminho mínimo e existência de circuito negativo:");

        btnDistanciaECaminhoMinimo.setText("Obter");
        btnDistanciaECaminhoMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistanciaECaminhoMinimoActionPerformed(evt);
            }
        });

        txtDistanciaECaminhoMinimo.setEditable(false);
        txtDistanciaECaminhoMinimo.setColumns(20);
        txtDistanciaECaminhoMinimo.setRows(5);
        jScrollPane7.setViewportView(txtDistanciaECaminhoMinimo);

        cbCalcularFloydCompleto.setText("Calcular para todos os vértices de destino possíveis");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(btnDistanciaECaminhoMinimo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCalcularFloydCompleto)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDistanciaECaminhoMinimo)
                    .addComponent(cbCalcularFloydCompleto))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Página 3", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Árvore geradora mínima:");

        btnArvoreGeradoraMinima.setText("Obter");
        btnArvoreGeradoraMinima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArvoreGeradoraMinimaActionPerformed(evt);
            }
        });

        txtArvoreGeradoraMinima.setEditable(false);
        txtArvoreGeradoraMinima.setColumns(20);
        txtArvoreGeradoraMinima.setRows(5);
        jScrollPane8.setViewportView(txtArvoreGeradoraMinima);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Cadeia euleriana:");

        btnCadeiaEuleriana.setText("Obter");
        btnCadeiaEuleriana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadeiaEulerianaActionPerformed(evt);
            }
        });

        txtCadeiaEuleriana.setEditable(false);
        txtCadeiaEuleriana.setColumns(20);
        txtCadeiaEuleriana.setRows(5);
        jScrollPane9.setViewportView(txtCadeiaEuleriana);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Conjunto independente:");

        btnConjuntoIndependente.setText("Obter");
        btnConjuntoIndependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConjuntoIndependenteActionPerformed(evt);
            }
        });

        txtConjuntoIndependente.setEditable(false);
        txtConjuntoIndependente.setColumns(20);
        txtConjuntoIndependente.setRows(5);
        jScrollPane10.setViewportView(txtConjuntoIndependente);

        cbConjuntoIndependenteOrdenacaoAleatoria.setText("Ordenação aleatória");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane9)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnArvoreGeradoraMinima))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCadeiaEuleriana))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConjuntoIndependente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbConjuntoIndependenteOrdenacaoAleatoria)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(btnArvoreGeradoraMinima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(btnCadeiaEuleriana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(btnConjuntoIndependente)
                    .addComponent(cbConjuntoIndependenteOrdenacaoAleatoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Página 4", jPanel9);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecionar", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aresta ou par de vértices", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Vértice de Origem:");

        txtVerticeOrigemAresta.setEnabled(false);
        txtVerticeOrigemAresta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtVerticeOrigemArestaStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Vértice de Destino:");

        txtVerticeDestinoAresta.setEnabled(false);
        txtVerticeDestinoAresta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtVerticeDestinoArestaStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVerticeDestinoAresta)
                    .addComponent(txtVerticeOrigemAresta))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtVerticeOrigemAresta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtVerticeDestinoAresta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vértice", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        txtVerticeUnitario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtVerticeUnitario.setEnabled(false);
        txtVerticeUnitario.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtVerticeUnitarioStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVerticeUnitario)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVerticeUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Arquivo entrada:");

        btnSelecionarArquivoSaida.setText("Selecionar");
        btnSelecionarArquivoSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarArquivoSaidaActionPerformed(evt);
            }
        });

        jButton2.setText("Ler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Arquivo saída:");

        btnSelecionarArquivoEntrada.setText("Selecionar");
        btnSelecionarArquivoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarArquivoEntradaActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(txtArquivoEntrada, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnSelecionarArquivoSaida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtArquivoSaida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnSelecionarArquivoEntrada, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelecionarArquivoEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArquivoEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelecionarArquivoSaida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArquivoSaida)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtArquivoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionarArquivoEntrada)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtArquivoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionarArquivoSaida))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu1.setText("Arquivo");

        jMenuItem4.setText("Ver grafo atual");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Outros");

        jMenuItem2.setText("Sobre");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarArquivoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarArquivoEntradaActionPerformed
        if(jFileChooser1.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION){
            String caminho = jFileChooser1.getSelectedFile().getAbsolutePath();

            if(caminho != null){
                txtArquivoEntrada.setText(caminho);
            }
        }
    }//GEN-LAST:event_btnSelecionarArquivoEntradaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        grafo = new Grafo();
        nome_arquivo_lido = txtArquivoEntrada.getText();
        grafo.lerArquivo(nome_arquivo_lido);
        if(grafo.getArquivoFoiLido()){
            JOptionPane.showMessageDialog(null, "Arquivo lido com sucesso!");
            habilitarOperacoes();
            btnEscreverEmArquivo.setEnabled(true);
            if(txtArquivoSaida.getText().isEmpty()){
                File directory = new File(OUTPUT_PATH);
                if(!directory.exists()){
                    directory.mkdir();
                }
                String path = OUTPUT_PATH + FILE_SEPARATOR + "out_" + jFileChooser1.getSelectedFile().getName();
                txtArquivoSaida.setText(path);
            }
            
        } else{
            JOptionPane.showMessageDialog(null, "O arquivo não foi lido...", "Erro", JOptionPane.ERROR_MESSAGE);
            nome_arquivo_lido = "";
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSelecionarArquivoSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarArquivoSaidaActionPerformed
        if(jFileChooser2.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION){
            String caminho = jFileChooser2.getSelectedFile().getAbsolutePath();

            if(caminho != null){
                txtArquivoSaida.setText(caminho);
            }
        }
    }//GEN-LAST:event_btnSelecionarArquivoSaidaActionPerformed

    private void btnEscreverEmArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscreverEmArquivoActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Você deseja escrever as informações da área de texto "
                + "Saída no arquivo:" + Grafo.QUEBRA_DE_LINHA + "\"" + txtArquivoSaida.getText() + "\"") == JOptionPane.YES_OPTION){
            String str = grafo.escreveResultadosEmArquivo(txtArquivoSaida.getText(), txtSaida.getText());
            if(str.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não foi possível escrever no arquivo...", "Erro", JOptionPane.ERROR_MESSAGE);
            } else{
                JOptionPane.showMessageDialog(null, str);
            }
        }        
    }//GEN-LAST:event_btnEscreverEmArquivoActionPerformed

    private void btnLimparTextoSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTextoSaidaActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Você tem certeza de que deseja limpar o texto de saída?") == JOptionPane.YES_OPTION){
            txtSaida.setText("");
        }
    }//GEN-LAST:event_btnLimparTextoSaidaActionPerformed

    private void btnGetGrauVerticeEVizinhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetGrauVerticeEVizinhosActionPerformed
        txtGrauVerticeEVizinhos.setText(grafo.toStringGrauVerticeEVizinhos((Integer)txtVerticeUnitario.getValue()));
        imprimeNaAreaDeSaida(txtGrauVerticeEVizinhos.getText());
    }//GEN-LAST:event_btnGetGrauVerticeEVizinhosActionPerformed

    private void txtVerticeUnitarioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtVerticeUnitarioStateChanged
        validaSpinnerVertices(txtVerticeUnitario);
    }//GEN-LAST:event_txtVerticeUnitarioStateChanged

    private void txtVerticeDestinoArestaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtVerticeDestinoArestaStateChanged
        validaSpinnerVertices(txtVerticeDestinoAresta);
    }//GEN-LAST:event_txtVerticeDestinoArestaStateChanged

    private void txtVerticeOrigemArestaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtVerticeOrigemArestaStateChanged
        validaSpinnerVertices(txtVerticeOrigemAresta);
    }//GEN-LAST:event_txtVerticeOrigemArestaStateChanged

    private void btnGetTamanhoGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTamanhoGrafoActionPerformed
        int tamanho = grafo.getTamanho();
        txtTamanhoGrafo.setText("" + tamanho);
        imprimeNaAreaDeSaida(grafo.toStringTamanho());
    }//GEN-LAST:event_btnGetTamanhoGrafoActionPerformed

    private void btnGetOrdemGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetOrdemGrafoActionPerformed
        int ordem = grafo.getOrdem();
        txtOrdemGrafo.setText("" + ordem);
        imprimeNaAreaDeSaida(grafo.toStringOrdem());
    }//GEN-LAST:event_btnGetOrdemGrafoActionPerformed

    private void btnIsBipartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsBipartidoActionPerformed
        String resposta = grafo.toStringIsBipartido();
        txtIsBipartido.setText(resposta);
        imprimeNaAreaDeSaida(resposta);
    }//GEN-LAST:event_btnIsBipartidoActionPerformed

    private void btnIsArticulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsArticulacaoActionPerformed
        String resposta = grafo.toStringIsArticulacao((Integer) txtVerticeUnitario.getValue());
        txtIsArticulacao.setText(resposta);
        imprimeNaAreaDeSaida(resposta);
    }//GEN-LAST:event_btnIsArticulacaoActionPerformed

    private void btnIsPonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsPonteActionPerformed
        Integer origem, destino;
        origem = (Integer) txtVerticeOrigemAresta.getValue();
        destino = (Integer) txtVerticeDestinoAresta.getValue();
        String resposta = grafo.toStringIsPonte(new Aresta<>(origem, destino));
        txtIsPonte.setText(resposta);
        imprimeNaAreaDeSaida(resposta);
    }//GEN-LAST:event_btnIsPonteActionPerformed

    private void btnBuscaProfundidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaProfundidadeActionPerformed
        String resposta = grafo.toStringBuscaEmProfundidade((Integer) txtVerticeUnitario.getValue());
        txtBuscaProfundidade.setText(resposta);
        imprimeNaAreaDeSaida(resposta);
    }//GEN-LAST:event_btnBuscaProfundidadeActionPerformed

    private void btnComponentesConexasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComponentesConexasActionPerformed
        String resposta = grafo.toStringComponentesConexas();
        txtComponentesConexas.setText(resposta);
        imprimeNaAreaDeSaida(resposta);
    }//GEN-LAST:event_btnComponentesConexasActionPerformed

    private void btnBuscaLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaLarguraActionPerformed
       String resposta = grafo.toStringBuscaEmLargura((Integer) txtVerticeUnitario.getValue());
       txtBuscaLargura.setText(resposta);
       imprimeNaAreaDeSaida(resposta);
    }//GEN-LAST:event_btnBuscaLarguraActionPerformed

    private void btnDistanciaECaminhoMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistanciaECaminhoMinimoActionPerformed
        String resposta = grafo.toStringDistanciaECaminhoMinimo((Integer) txtVerticeOrigemAresta.getValue(), (Integer) txtVerticeDestinoAresta.getValue(), cbCalcularFloydCompleto.isSelected());
        txtDistanciaECaminhoMinimo.setText(resposta);
        imprimeNaAreaDeSaida(resposta);
    }//GEN-LAST:event_btnDistanciaECaminhoMinimoActionPerformed

    private void btnArvoreGeradoraMinimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArvoreGeradoraMinimaActionPerformed
        String resposta = grafo.toStringArvoreGeradoraMinima();
        txtArvoreGeradoraMinima.setText(resposta);
        imprimeNaAreaDeSaida(resposta);
    }//GEN-LAST:event_btnArvoreGeradoraMinimaActionPerformed

    private void btnCadeiaEulerianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadeiaEulerianaActionPerformed
        String resposta = grafo.toStringCadeiaEulerianaFechada();
        txtCadeiaEuleriana.setText(resposta);
        imprimeNaAreaDeSaida(resposta);
    }//GEN-LAST:event_btnCadeiaEulerianaActionPerformed

    private void btnConjuntoIndependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConjuntoIndependenteActionPerformed
        String resposta = grafo.toStringConjuntoIndependente(cbConjuntoIndependenteOrdenacaoAleatoria.isSelected());
        txtConjuntoIndependente.setText(resposta);
        imprimeNaAreaDeSaida(resposta);
    }//GEN-LAST:event_btnConjuntoIndependenteActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(null, 
                "<html><body><h1>Biblioteca - Grafos</h1><h3>-> Versão 1.0</h3><h2>Criado por:</h2><h3> -> Daniel Freitas Martins - 2304 <br /> -> Naiara Cristiane dos Reis Diniz - 3005", "Sobre", 
                JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if(grafo.getOrdem() > 100){
            if(!(JOptionPane.showConfirmDialog(null, "- Contém muitos vértices para realizar a impressão... Deseja mostrar assim mesmo?") == JOptionPane.YES_OPTION)){
                return;
            }            
        }
        
        JTextPane txtpane = new JTextPane();
        JScrollPane jscp = new JScrollPane(txtpane);
        txtpane.setContentType("text/html");
        txtpane.setText(grafo.toStringMatrizValores());
        
        //((HTMLDocument)txtarea.getDocument()).setPreservesUnknownTags(false);
        jscp.setPreferredSize(new Dimension(800, 600));
        JOptionPane.showMessageDialog(null, jscp, "Grafo atual", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    void imprimeNaAreaDeSaida(String str){
        txtSaida.setText(txtSaida.getText().concat(str));
    }
    
    private void validaSpinnerVertices(JSpinner spinner){
        int valor = (Integer)spinner.getValue(), qtd_vertices = grafo.getOrdem();
        if(qtd_vertices == 0){
            valor = 0;
        } else{
            if(valor <= 0){
                valor = 1;
            } else{
                if(valor > qtd_vertices){
                    valor = qtd_vertices;
                }
            }
        }
        spinner.setValue(valor);
    }
    
    private void habilitarOperacoes(){
        int qtd_vertices = grafo.getOrdem();
        btnGetOrdemGrafo.setEnabled(true);
        btnGetTamanhoGrafo.setEnabled(true);
        txtVerticeUnitario.setEnabled(qtd_vertices > 0);
        txtVerticeUnitario.setValue(1 % (qtd_vertices + 1));
        txtVerticeOrigemAresta.setEnabled(qtd_vertices > 0);
        txtVerticeOrigemAresta.setValue(1 % (qtd_vertices + 1));
        txtVerticeDestinoAresta.setEnabled(qtd_vertices > 0);
        txtVerticeDestinoAresta.setValue(1 % (qtd_vertices + 1));            
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArvoreGeradoraMinima;
    private javax.swing.JButton btnBuscaLargura;
    private javax.swing.JButton btnBuscaProfundidade;
    private javax.swing.JButton btnCadeiaEuleriana;
    private javax.swing.JButton btnComponentesConexas;
    private javax.swing.JButton btnConjuntoIndependente;
    private javax.swing.JButton btnDistanciaECaminhoMinimo;
    private javax.swing.JButton btnEscreverEmArquivo;
    private javax.swing.JButton btnGetGrauVerticeEVizinhos;
    private javax.swing.JButton btnGetOrdemGrafo;
    private javax.swing.JButton btnGetTamanhoGrafo;
    private javax.swing.JButton btnIsArticulacao;
    private javax.swing.JButton btnIsBipartido;
    private javax.swing.JButton btnIsPonte;
    private javax.swing.JButton btnLimparTextoSaida;
    private javax.swing.JButton btnSelecionarArquivoEntrada;
    private javax.swing.JButton btnSelecionarArquivoSaida;
    private javax.swing.JCheckBox cbCalcularFloydCompleto;
    private javax.swing.JCheckBox cbConjuntoIndependenteOrdenacaoAleatoria;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtArquivoEntrada;
    private javax.swing.JTextField txtArquivoSaida;
    private javax.swing.JTextArea txtArvoreGeradoraMinima;
    private javax.swing.JTextArea txtBuscaLargura;
    private javax.swing.JTextArea txtBuscaProfundidade;
    private javax.swing.JTextArea txtCadeiaEuleriana;
    private javax.swing.JTextArea txtComponentesConexas;
    private javax.swing.JTextArea txtConjuntoIndependente;
    private javax.swing.JTextArea txtDistanciaECaminhoMinimo;
    private javax.swing.JTextArea txtGrauVerticeEVizinhos;
    private javax.swing.JTextField txtIsArticulacao;
    private javax.swing.JTextArea txtIsBipartido;
    private javax.swing.JTextField txtIsPonte;
    private javax.swing.JTextField txtOrdemGrafo;
    private javax.swing.JTextArea txtSaida;
    private javax.swing.JTextField txtTamanhoGrafo;
    private javax.swing.JSpinner txtVerticeDestinoAresta;
    private javax.swing.JSpinner txtVerticeOrigemAresta;
    private javax.swing.JSpinner txtVerticeUnitario;
    // End of variables declaration//GEN-END:variables
}
